# Generated by Django 3.2.9 on 2021-12-27 08:08

import datetime

import django.db.models.deletion
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("decks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                (
                    "bucket",
                    models.IntegerField(
                        choices=[
                            (1, "1 Day"),
                            (2, "3 Day"),
                            (3, "7 Day"),
                            (4, "16 Day"),
                            (5, "30 Day"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "next_review_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2021, 12, 27, 8, 8, 1, 548121, tzinfo=utc
                        )
                    ),
                ),
                ("last_review_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="decks.deck"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
